#!/usr/bin/env bash

function build_image () {
  local image_name=${1}
  local tag=${2:-latest}
  docker build --pull --file Dockerfile-build --tag ${image_name}:${tag} . \
      && docker push ${image_name}:${tag}
}

function get-chrome-version () {
  headers=$(curl --silent -LI "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb")
  echo "$headers" | grep Last-Modified | sed -e 's/Last-Modified: //'
}

function get-chromedriver-version () {
  curl --silent -L http://chromedriver.storage.googleapis.com/LATEST_RELEASE | xargs
}

CHROME_VERSION=$(get-chrome-version)
CHROMEDRIVER_VERSION=$(get-chromedriver-version)

#exit 1

sed -E \
    -e "s/ENV GOOGLE_CHROME_DATE .+/ENV GOOGLE_CHROME_DATE ${CHROME_VERSION}/" \
    -e "s/ENV CHROMEDRIVER_VERSION .+/ENV CHROMEDRIVER_VERSION ${CHROMEDRIVER_VERSION}/" \
    Dockerfile > Dockerfile-build

#cp Dockerfile Dockerfile-build
build_image turistpro/selenium-cucumber
