#!/usr/bin/env bash
set -e

apt-get update
curl -L https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb \
    --output /tmp/google-chrome-stable_current_amd64.deb
dpkg -i /tmp/google-chrome-stable_current_amd64.deb || apt-get -f -y install
rm -rf /var/lib/apt/lists/*

rm /tmp/google-chrome-stable_current_amd64.deb

curl -L http://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip \
    --output /tmp/chromedriver.zip
cd /usr/local/bin
unzip /tmp/chromedriver.zip
rm /tmp/chromedriver.zip
cd -
